import { FaInstagram, FaPaintBrush, FaTelegramPlane, FaWhatsapp } from "react-icons/fa";
import { MdOutlineEmail } from "react-icons/md";
import { ArtworkActions } from "./ArtworkActions";
import { Hero } from "./Hero";
import { assetPath } from "./assetPath";

const works = [
  { title: "«Девочка и гуси»", image: assetPath("images/artworks/devochka-i-gusi.jpg"), interior: assetPath("images/interiors/devochka-i-gusi.jpg"), size: "80 х 60 см.", price: "260 000 руб." },
  { title: "«Нежность»", image: assetPath("images/artworks/nezhnost.jpg"), interior: assetPath("images/interiors/nezhnost.jpg"), size: "35 х 25 см.", price: "25 000 руб." },
  { title: "«Знакомство»", image: assetPath("images/artworks/znakomstvo.jpg"), interior: assetPath("images/interiors/znakomstvo.jpg"), size: "80 х 50 см.", price: "76 000 руб." },
  { title: "«Аммонит»", image: assetPath("images/artworks/ammonit.jpg"), interior: assetPath("images/interiors/ammonit-dark.jpg"), size: "100 х 80 см.", price: "236 900 руб." },
  { title: "«Театр теней»", image: assetPath("images/artworks/teatr-teney.jpg"), interior: assetPath("images/interiors/teatr-teney.jpg"), size: "80 х 60 см.", price: "280 000 руб." },
];
function Heading({ children }: { children: React.ReactNode }) { return <><h2 className="work-heading">{children}</h2><div className="heading-rule"><span>✦</span></div></>; }
export default function Home() { return <main>
  <Hero />
  <section className="catalog"><div className="catalog-grid">{works.map((w)=><article className="catalog-work" key={w.title}><img src={w.image} alt={w.title}/><div className="catalog-copy"><h3>{w.title}</h3><p>Холст на подрамнике, Лён<br/>Масло<br/>{w.size}</p></div><ArtworkActions work={w}/></article>)}</div></section>
  <section className="story story-light tenderness"><div className="story-copy top-left"><Heading>«Нежность»</Heading><p className="details">Холст на подрамнике, Лён<br/>Масло<br/>35 х 25 см.</p><p className="dropcap">Работа выполнена в экспрессивной живописной манере. Видимые мазки кисти не стремятся к фотографической точности, а создают ощущение живого движения и эмоциональной глубины. Тёплая палитра из охристых, розовых, кремовых и коричневых оттенков наполняет полотно уютом и светом, подчёркивая атмосферу спокойствия, безопасности и безусловной любви.</p><p className="dropcap">Контраст между мягкими светлыми оттенками кожи и более глубокими тёмными тонами волос создаёт выразительный акцент на эмоциональном центре композиции.</p></div><img className="art tall right-art" src={assetPath("images/artworks/nezhnost.jpg")} alt="Картина Нежность"/><img className="interior left-interior" src={assetPath("images/interiors/nezhnost.jpg")} alt="Нежность в интерьере"/><div className="story-copy bottom-right"><p className="dropcap">Эта картина передаёт один из самых трогательных и тихих моментов человеческой жизни — нежность между матерью и новорождённым ребёнком, о безмолвной заботе, тепле и любви, которые невозможно выразить словами.</p><p className="dropcap">Произведение вызывает чувство умиротворения и напоминает о ценности самых простых, но самых значимых моментов жизни.</p></div></section>
  <section className="story story-olive acquaintance"><img className="interior top-interior" src={assetPath("images/interiors/znakomstvo.jpg")} alt="Знакомство в интерьере"/><div className="story-copy top-right"><Heading>«Знакомство»</Heading><p className="details">Холст на подрамнике, Лён<br/>Масло<br/>80 х 50 см.</p><p className="dropcap">Это один из тех моментов детства, когда весь мир может сузиться до одного маленького события. В этой работе мне хотелось запечатлеть яркие, позитивные эмоции и напоминание о времени, когда самые простые вещи казались чудом.</p><p className="dropcap">Я использовала свободную, живописную манеру письма с выразительными мазками и палитрой теплых коричневых, золотистых и глубоких синих оттенков. Свет и цвет не только формируют пространство, но и передают эмоциональное состояние героев.</p></div><div className="story-copy bottom-left"><p className="dropcap">Эта картина передает ощущение тихого, почти сказочного момента встречи двух миров — детского любопытства и беззащитности маленького животного.</p><p className="dropcap">Она напоминает о времени, когда мир открывался через простое наблюдение, а маленькая встреча могла казаться целым событием.</p></div><img className="art wide bottom-art" src={assetPath("images/artworks/znakomstvo.jpg")} alt="Картина Знакомство"/></section>
  <section className="story story-light geese"><div className="story-copy top-left"><Heading>«Девочка и гуси»</Heading><p className="details">Холст на подрамнике, Лён<br/>Масло<br/>80 х 50 см.</p><p className="dropcap">Картина энергетически заряжена состоянием живого движения. Она словно говорит: «Не жди идеального момента. Иди.» перестань спрашивать разрешения у мира и просто иди туда, куда зовёт сердце.</p><p className="dropcap">Она напоминает, что жизнь не должна быть тяжёлой. Что можно выбирать радость. Можно доверять себе. Можно идти вперёд легко, даже если впереди неизвестность. Эта картина словно наполняет дом свежим воздухом.</p></div><img className="art tall right-art" src={assetPath("images/artworks/devochka-i-gusi.jpg")} alt="Картина Девочка и гуси"/><img className="interior left-interior" src={assetPath("images/interiors/devochka-i-gusi.jpg")} alt="Девочка и гуси в интерьере"/><div className="story-copy bottom-right"><p className="dropcap">При появлении этой картины дома, пространство начнет напоминать о том, что жизнь — это не борьба, а движение.</p><p className="dropcap">Она возвращает вкус к простым вещам, пробуждает вдохновение и помогает выйти из состояния «надо» в состояние «хочу».</p></div></section>
  <section className="story story-warm shadows"><img className="art tall left-art" src={assetPath("images/artworks/teatr-teney.jpg")} alt="Картина Театр теней"/><div className="story-copy top-right"><Heading>«Театр теней»</Heading><p className="details">Холст на подрамнике, Лён<br/>Масло<br/>80 х 60 см.</p><p className="dropcap">Белое полотно становится сценой, а тень — главным героем. Для взрослого это игра рук, для ребенка — встреча с существом, которое действительно существует в этот момент. Картина говорит о том коротком времени, когда воображение сильнее знания, а любая тень может стать началом целой вселенной.</p><p className="dropcap">Мазок густой, пастозный, напоминает живопись конца XIX — начала XX века. Фактура не скрывается, наоборот — становится частью изображения.</p></div><div className="story-copy bottom-left"><p className="dropcap">Эта картина интересна тем, что она одновременно читается как бытовая сцена и как метафора. Ее смысл рождается не столько из сюжета, сколько из отношений между масштабами, светом, фактурой и взглядом ребенка.</p><p className="dropcap">Работа напоминает, что воображение не дополняет реальность, а создает ее.</p></div><img className="interior right-interior" src={assetPath("images/interiors/teatr-teney.jpg")} alt="Театр теней в интерьере"/></section>
  <section className="story story-light ammonite">
    <div className="story-copy top-left"><Heading>«Аммонит»</Heading><p className="details">Холст на подрамнике, Лён<br/>Масло<br/>100 х 80 см.</p><p className="dropcap">Картина предлагает не просто смотреть на изображение, а погружаться в него.</p><p className="dropcap">Глубина раскрывается постепенно. Сначала взгляд воспринимает целостную форму, затем начинает следовать за спиралью, погружаясь всё глубже — от внешнего пространства к центру, от видимого к невидимому, от материи к смыслу.</p><p className="dropcap">Эта картина — путешествие внутрь себя, где цикличность времени становится пространством для расширения сознания, а глубина восприятия помогает увидеть суть происходящего.</p></div>
    <img className="art ammonite-art" src={assetPath("images/artworks/ammonit.jpg")} alt="Картина Аммонит"/>
    <img className="interior ammonite-interior-dark" src={assetPath("images/interiors/ammonit-dark.jpg")} alt="Аммонит в тёмном интерьере"/>
    <div className="story-copy ammonite-copy-right"><p className="dropcap">Цикличность здесь не означает повторение. Каждый виток похож на предыдущий, но никогда не является его точной копией. Время возвращает нас к знакомым состояниям, однако каждый раз мы видим их уже из другой точки — с другой глубиной, другим опытом и другим взглядом.</p><p className="dropcap">Как раковина аммонита хранит следы всех предыдущих витков роста, так и человек несёт в себе опыт прошлого, который формирует его настоящее и открывает путь в будущее.</p></div>
    <div className="story-copy ammonite-copy-bottom"><p className="dropcap">Эта работа приглашает замедлиться и почувствовать: время не движется только вперёд — оно разворачивается по спирали. Мы возвращаемся к похожим событиям, но каждый раз воспринимаем их глубже, потому что изменились сами.</p></div>
    <img className="interior ammonite-interior-light" src={assetPath("images/interiors/ammonit-light.jpg")} alt="Аммонит в светлом интерьере"/>
  </section>
  <footer className="contact"><div className="contact-disc"><div className="vine small">⌇﹏⌇﹏⌇﹏⌇</div><div className="contact-title"><h2>CONTACT ME</h2><div className="contact-underline" aria-hidden="true"><FaPaintBrush/></div></div></div><div className="contacts"><a href="mailto:ursova.al@mail.ru" aria-label="Написать Алёне по электронной почте"><MdOutlineEmail aria-hidden="true"/>ursova.al@mail.ru</a><a href="https://wa.me/79613698369" target="_blank" rel="noreferrer" aria-label="Написать Алёне в WhatsApp"><FaWhatsapp aria-hidden="true"/>8(961)369-8-369</a><a href="https://t.me/Alena_Ursova" target="_blank" rel="noreferrer" aria-label="Написать Алёне в Telegram"><FaTelegramPlane aria-hidden="true"/>@Alena_Ursova</a><a href="https://instagram.com/alena_ursova_" target="_blank" rel="noreferrer" aria-label="Открыть Instagram Алёны"><FaInstagram aria-hidden="true"/>alena_ursova_</a></div></footer>
</main>; }
